### ISSUE TITLE
how can I install test_requirements and run test?

### ISSUE THREAD

**Issue by chobijaeyu** [mandeepbhutani/cookiecutter-pyqt5#6]
should I run 
`pip install coverage`
`pip install coveralls`
`pip install pytest`
`pip install pytest-cov`
`pip install pytest-faulthandler`
`pip install pytest-mock`
`pip install pytest-qt`
`pip install pytest-xvf`
and `pytest`?
or there is better way?

thanks for your time

**Comment by mandeep** [comment]
Are you trying to test this package? Or are you trying to test the package that this cookiecutter outputs?

**Comment by chobijaeyu** [comment]
thanks for reply

I want to test pyqt base on this cookiecutter outputs.

**Comment by mandeep** [comment]
I see.

I believe you can just run `python setup.py test` and the test requirements will be installed. Then you can run `pytest` and it will run all the tests.

Thanks for bringing this to my attention. I should update the README to include this information.

**Comment by chobijaeyu** [comment]
when I run `python setup.py test`
I get some error here.

Is I missing something?

![スクリーンショット 2019-08-13 11 01 08](https://user-images.githubusercontent.com/25117318/62909991-c6989a80-bdb9-11e9-8137-d42c936f52db.png)


but I can run `pytest` when I manually `pip install ***`.

**Comment by mandeep** [comment]
It looks like setup.py does not install the packages from test_requires. I believe this to be a problem with setuptools. Also, not being able to find the tests module is due to a typo in test_suite in setup.py. I'll remove the use of test_requires from setup.py and instead use a requirements-dev.txt file. For now I believe you have to install each test package manually.

**Comment by chobijaeyu** [comment]
thank you ,really help me a lot.
